blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('detail/<str:slug>/', BlogDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from pytils.translit import slugify


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    body = models.TextField(verbose_name='Статья')
    slug = models.CharField(max_length=50, verbose_name='slug', null=True, blank=True, unique=True)
    preview = models.ImageField(upload_to='imj_blog/', verbose_name='Изображение', null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_publication = models.BooleanField(default=False, verbose_name='Опубликовано')
    views_count = models.IntegerField(verbose_name='Количество просмотров', default=0)

    def save(self, *args, **kwargs):
        """Переопределен метод save. При создании сущности сразу заполняется
        поле slug."""
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}, {self.create_date}, {self.is_publication}'

    class Meta:
        verbose_name = 'Блог'

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    """Создание сущности с полями:
    title: str
    body: text
    preview: img"""
    model = Blog
    fields = ('title', 'body', 'preview',)
    success_url = reverse_lazy('blog:list')


class BlogUpdateView(UpdateView):
    """Update существующей сущности"""
    model = Blog
    fields = ('body', 'preview',)

    # success_url = reverse_lazy('blog:list')

    def get_success_url(self):
        """Переопределен метод, для перенаправления на статью после обновления."""
        return reverse('blog:detail', args=[self.object.slug])


class BlogListView(ListView):
    """Просмотр всех сущностей модели"""
    model = Blog


class BlogDetailView(DetailView):
    """Просмотр одной сущности из модели"""
    model = Blog

    def get_object(self, queryset=None):
        """Переопределение метода для подсчета количества просмотров"""
        self.object = super().get_object(queryset)
        # Счетчик просмотров
        self.object.views_count += 1
        if self.object.views_count == 100:
            # Отправка письма при достижении счетчиком отметки 100
            send_mail(
                'Поздравляем!!!',
                'Поздравляем! Статья набрала более ста просмотров',
                '', # your email
                [''], # to@exampl.com
                fail_silently=False,
            )
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    """Удаление объекта"""
    model = Blog
    success_url = reverse_lazy('blog:list')


def toggle_activity(request, pk):
    """Функция для переключения статуса опубликованное/неопубликованное"""
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_publication:
        blog_item.is_publication = False
    else:
        blog_item.is_publication = True
    blog_item.save()
    return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
<div class='row'>
    <div class="col=6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Хотите удалить статью "{{ object.title }}"?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">COOLStore</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <img src="/media/{{ object.preview }}" class="card-img-top" style="width: 18rem;"/>
            <div class="card-body">
                <h5 class="card-title" style="margin-top: 20px;">{{ object.title }}</h5>
                <p class="card-text" style="margin-top: 20px;">{{ object.body }}</p>
                <p class="card-text" style="margin-top: 20px;">Просмотры: {{ object.views_count }}</p>

                <a href="{% url 'blog:list' %}" class="btn btn-primary">Вернуться</a>
                <a href="{% url 'blog:edit' object.pk %}" class="btn btn-warning">Редактировать</a>
                    {% if object.is_publication %}
                        <a href="{% url 'blog:toggle_activity' object.pk %}" class="btn btn-info">Снять с публикации</a>
                    {% else %}
                        <a href="{% url 'blog:toggle_activity' object.pk %}" class="btn btn-secondary">Опубликовать</a>
                    {% endif %}
                <a href="{% url 'blog:delete' object.pk %}" class="btn btn-danger">Удалить</a>
            </div>
        </div>
    </div>
    {% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
<div class='row'>
    <div class="col=6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блоги о производителях...</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4" style="width: 18rem;">
                <img src="/media/{{ object.preview }}" class="card-img-top" style="width: 18rem;"/>
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text"></p>
                        <p class="card-text">{{ object.body|slice:50 }}</p>
                    {% if object.is_publication %}
                        <p class="card-text" style="margin-top: 20px;">Просмотры: {{ object.views_count }}</p>
                        <a href="{% url 'blog:detail' object.slug %}" class="btn btn-primary">Читать статью</a>
                    {% else %}
                        <p class="card-text" style="margin-top: 20px;">Неопубликованное</p>
                        <a href="{% url 'blog:detail' object.slug %}" class="btn btn-primary">Редактировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row text-center">
        <div class="col-12">
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
        </div>
    </div>
</div>
{% endblock %}