blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('detail/<str:slug>/', BlogDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, mail_verification, UserUpdateView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/newpassword/', generate_new_password, name='generate_new_password'),
    path('register/verification/<int:pk>', mail_verification, name='mail_verification'),
]

users/models.py
from random import randint

from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')

    phone = models.CharField(max_length=50, verbose_name='Телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULLABLE)
    code = models.CharField(max_length=10, verbose_name='Код для верификации')
    is_active = models.BooleanField(default=False, verbose_name='Верификация')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = str(randint(100000, 999999))
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserUpdateForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'country', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"

    def form_valid(self, form):
        self.object = form.save()
        send_mail(
            subject='Поздравляем с успешной регистрацией!',
            message=f'Для успешного завершения регистрации введите на сайте VerificationCode {self.object.code}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email]
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:mail_verification', kwargs={'pk': self.object.pk})


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(10)])
    send_mail(
        subject='Сброс пароля',
        message=f'Ваш новый пароль - {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('catalog:products'))


def mail_verification(request, pk):
    user = User.objects.get(pk=pk)
    if request.method == 'POST':
        code = request.POST.get('code')
        if code == user.code:
            user.is_active = True
            user.save()
            return redirect(reverse('catalog:products'))
        else:
            raise ValueError('Неправильно введен код')
    return render(request, 'users/verification.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">Войти в учетную запись</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
        </div>
    </div>

    {% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <h3 class="card-header">Регистрация</h3>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
                </form>
            </div>
        </div>
    </div>

    {% endblock %}

users/templates/users/verification.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">Подтверждение почты</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" name="code" class="form-control" id="name" placeholder="Введите код"
                               required>
                    </div>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}