blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('detail/<str:slug>/', BlogDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig

from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    to_published, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('contacts/', contacts, name='contacts'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view'),
    path('create/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='update_product'),
    path('to_published/<int:pk>/', to_published, name='to_published'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, mail_verification, UserUpdateView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/newpassword/', generate_new_password, name='generate_new_password'),
    path('register/verification/<int:pk>', mail_verification, name='mail_verification'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='media/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    data_creation = models.DateField(verbose_name='Дата создания')
    last_modified_date = models.DateField(verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='Публикация')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Продавец')

    def __str__(self):
        return f'{self.name}, {self.description}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            (
                'set_published',
                'Can publish posts'
            )
        ]


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    # created_at = models.CharField(verbose_name='create', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Contact(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    phone = models.IntegerField(verbose_name='Телефон')

    def __str__(self):
        return f'{self.last_name} {self.first_name} Контактный номер:{self.phone}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.IntegerField(verbose_name='Номер версии')
    version_name = models.CharField(max_length=200, verbose_name='Название версии')
    is_current = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.product}, {self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_current' and field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                       'радар']

    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        for word in self.forbidden_words:
            if word in cleaned_data:
                raise forms.ValidationError(f'Недопустимые слова {self.forbidden_words}')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in self.forbidden_words:
            if word in cleaned_data:
                raise forms.ValidationError(f'Недопустимые слова {self.forbidden_words}')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Contact, Version, Category
from catalog.services import get_cached_categories


class ProductCreateView(LoginRequiredMixin, CreateView):
    """Создание продукта"""
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование продукта"""
    model = Product
    form_class = ProductForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('catalog:update_product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        counter = 0
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        for f in formset:
            if f.initial.get('is_current'):
                counter += 1
            else:
                continue
        if counter > 1:
            raise ValidationError('Активная версия может быть только одна')
        return super().form_valid(form)


class ProductListView(ListView):
    """Просмотр всех объектов модели Product"""
    model = Product

    def get_context_data(self, **kwargs):
        """Переопределение метода, version_set в коде является менеджером связей для модели Product,
        создается для всех моделей, имеющих связи ForeignKey (Это памятка для себя)"""
        # Вызываем родительский класс с данными
        context = super().get_context_data(**kwargs)

        for product in context['object_list']:
            active_version = product.version_set.filter(is_current=True).first()
            if active_version:
                product.active_version_number = active_version.version_number
            else:
                product.active_version_number = None
        return context


def contacts(request):
    contact = Contact.objects
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        with open('info.txt', 'a', encoding='utf-8') as f:
            f.write(f'Имя: {name}\nТелефон: {phone}\nСообщение: {message}\n')
    return render(request, 'catalog/contacts.html', {'contact': contact})


class ProductDetailView(LoginRequiredMixin, DetailView):
    """Просмотр одного объекта модели Product"""
    model = Product


@user_passes_test(lambda u: u.is_staff)
@permission_required('catalog.set_published')
def to_published(request, pk):
    """Функция для переключения статуса опубликованное/неопубликованное"""
    product_item = get_object_or_404(Product, pk=pk)
    if product_item.is_published:
        product_item.is_published = False
    else:
        product_item.is_published = True
    product_item.save()
    return redirect(reverse('catalog:view', args=[pk]))


class CategoryListView(ListView):
    """Просмотр всех объектов модели Category"""
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['categories'] = get_cached_categories()
        return context_data

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазин электроники COOLStore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <div class="col-9">
        <h5 class="my-0 mr-md-auto font-weight-normal">Магазин электроники COOLStore</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
            <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        </nav>
    </div>
    <div class="col-3">
        <nav class="ms-5">
            {% if user.is_authenticated %}
                <li><a href="{% url 'users:profile' %}">Профиль</a></li>
                <li><a href="{% url 'users:logout' %}">Выйти</a></li>
            {% else %}
                <li><a href="{% url 'users:login' %}">Вход</a></li>
                <li><a href="{% url 'users:register' %}">Регистрация</a></li>
            {% endif %}
        </nav>
    </div>
</div>

{% block content %}
{% endblock %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-3 col-md">
                COOLStore
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
            </div>
            <div class="col-3 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">COOLStore</h1>
    <p class="lead">COOLStore - отличное место наполненное гаджетами</p>
</div>


<div class="container">
    <div class="row text-center">
        {% for cat in categories %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4>Категория</h4>
                </div>
                <div class="card-body">
                    <h4 class="my-0 font-weight-normal">{{ cat.name }}</h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                        {% for contact in contact.all %}
                        <tr>
                            <td class="w-25">Имя</td>
                            <td>{{contact.first_name}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Фамилия</td>
                            <td>{{contact.last_name}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон</td>
                            <td>{{contact.phone}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">COOLStore</h1>
    <p class="lead">COOLStore - отличное место наполненное гаджетами</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name|truncatechars:30}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{object.price}} руб.</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{object.description|truncatechars:100}}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product' object.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">COOLStore</h1>
    <p class="lead">Описание продукта</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-12">
<!--            <img src="/media/{{ product.image }}" class="card-img-top" style="width: 18rem;"/>-->
            <img src="{% mediapath product.image %}" class="card-img-top" style="width: 18rem;"/>
            <div class="card-body">
                <h5 class="card-title" style="margin-top: 20px;">{{ product.name }}</h5>
                <p class="card-text" style="margin-top: 20px;">{{ product.description }}</p>
                <a href="/" class="btn btn-primary">К товарам</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">COOLStore</h1>
    <p class="lead">Описание продукта</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-12">
<!--            <img src="/media/{{ product.image }}" class="card-img-top" style="width: 18rem;"/>-->
            <img src="{% mediapath product.image %}" class="card-img-top" style="width: 18rem;"/>
            <div class="card-body">
                <h5 class="card-title" style="margin-top: 20px;">{{ product.name }}</h5>
                <p class="card-text" style="margin-top: 20px;">{{ product.description }}</p>
                <a href="/" class="btn btn-primary">К товарам</a>
                {% if perms.catalog.change_product or user == product.owner %}
                <a href="{% url 'catalog:update_product' object.pk %}" class="btn btn-warning">Редактировать</a>
                {% endif %}
                {% if perms.catalog.set_published %}
                {% if not product.is_published %}
                <a href="{% url 'catalog:to_published' object.pk %}" class="btn btn-success">Опубликовать</a>
                {% else %}
                <a href="{% url 'catalog:to_published' object.pk %}" class="btn btn-success">Снять с публикации</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class='col-6'>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Добавление нового товара</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products' %}">Выйти из редактирования</a>
                </div>
            </div>
        </div>
        <div class='col-6'>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Версия товара</h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not formloop.last %}
                        <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">COOLStore</h1>
    <p class="lead">COOLStore - отличное место наполненное гаджетами</p>
</div>
<div class="row text-center">
    <div class="col-12 mb-4">
        <a class="p-2 btn btn-outline-success" href="{% url 'catalog:create_product' %}">Добавить товар</a>
        <a class="p-2 btn btn-outline-success" href="{% url 'catalog:category' %}">Перейти к категориям</a>
    </div>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name|truncatechars:30}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{object.price}} руб.</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.description|truncatechars:100 }}</li>
                        <p><li>- {{ object.owner|default:'Без продавца' }}</li></p>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:view' object.pk %}">Подробнее</a>
                </div>
                <div class="card-footer">
                    {% if object.active_version_number  %}
                        <P class="my-0 font-weight-normal">Версия продукта: {{object.active_version_number}}</P>
                    {% else %}
                        <P class="my-0 font-weight-normal">Нет активных версий</P>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}